
---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Preparation
### forked and cloned RepData_PeerAssesment1 rep, and unzipped 'activity'

## Loading and preprocessing the data

```{r loading_and_processing}
activity <- read.csv('activity/activity.csv')

str(activity)

summary(activity)


```



## What is mean total number of steps taken per day?

<!-- "For this part of the assignment, you can ignore the missing values in the dataset."[https://github.com/rdpeng/RepData_PeerAssessment1/blob/master/README.md]


### "Make a histogram of the total number of steps taken each day"[https://github.com/rdpeng/RepData_PeerAssessment1/blob/master/README.md]

###Calculate and report the mean and median total number of steps taken per day
 -->   
    
```{r numberofsteps}
# generate histogram of number of steps
hist(activity$steps)


# calculate the mean number of steps (ignoring NAs):
mean(activity$steps, na.rm=TRUE)

# calculate the median number of steps (ignoring NAs):
median(activity$steps, na.rm=TRUE)
```


<!-- quoted from assignment
    Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

    Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps? -->

## What is the average daily activity pattern?
```{r dailypattern}

# calculate the average number of steps taken in each interval, averaged across all recorded days
require(dplyr)

mean_steps_per_interval <- summarise(group_by(activity, interval), m=mean(steps, na.rm=TRUE))

# plot mean steps per interval
plot(mean_steps_per_interval$m ~ mean_steps_per_interval$interval, type="l",
     main="Daily Activity Pattern", xlab="interval", ylab="mean # steps (across all days)"
     )
grid()


# calculate interval with maximum # steps, averaged across all recorded days
mean_steps_per_interval$interval[mean_steps_per_interval$m == max(mean_steps_per_interval$m, na.rm=TRUE)]

```

## Imputing missing values


```{r imputingNAs}


# calculate the total number observations (rows) with missing values
 sum(!complete.cases(activity))


# strategy for imputing missing values: replace NA values with mean value for that interval


# 1. find indices of NAs in activity

na_indices <- which(is.na(activity$steps))

intervalsNAindices <- activity$interval[na_indices]

# 2. look up mean # steps for each missing value, by using the missing value's interval number
# incorrect approach with attempt at vectorization
#replacements <- mean_steps_per_interval$m[intervalsNAindices == mean_steps_per_interval$interval]


# trying again with a for loop (there must be a better way to do this in R, any suggestions?)
replacements <- rep(0, length(intervalsNAindices))
for (i in  1:length(intervalsNAindices) ) {
    replacements[i] <- mean_steps_per_interval$m[mean_steps_per_interval$interval == intervalsNAindices[i]]
}

# 3.  create a new dataset and replace missing values with mean-per-interval values
activityImputed <- activity

activityImputed$steps <- replace(activity$steps, na_indices, replacements)

# 4. double-check for missing values
anyNA(activityImputed)

# 5. compare stats to original summary
summary(activityImputed)
```

   
```{r numberofstepsimputed}
# generate histogram with imputed-data dataset
hist(activityImputed$steps)

# calculate mean number of steps (ignoring NAs):
mean(activityImputed$steps, na.rm=TRUE)

# Median number of steps (ignoring NAs):
median(activityImputed$steps, na.rm=TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r weekpatterns}
# add new factor to distinguish weekends & weekdays
week_pattern <- factor(weekdays(as.Date(activityImputed$date)) %in% c("Saturday", "Sunday"))
levels(week_pattern)<- c("weekday", "weekend")  # false == 0 == weekday; true == 1 == weekend

activityImputed$week <- week_pattern

# seperate average per interval for weekends and weekday 

weekend_activity <- activityImputed[activityImputed$week=="weekend",]
weekday_activity <- activityImputed[activityImputed$week =="weekday",]


mean_activityImputed_weekends <- summarise(group_by(weekend_activity, interval), meanSteps=mean(steps))



mean_activityImputed_weekdays <- summarise(group_by(weekday_activity, interval), meanSteps=mean(steps))

# add column for weekend/weekday factors (used later in merged dataframe)
mean_activityImputed_weekends$week <- as.factor("weekend")
mean_activityImputed_weekdays$week <- as.factor("weekday")


# create dataframe for convenient plotting
#weekly_trends <- data.frame(interval=activityImputed)

weekly_trends <- merge(mean_activityImputed_weekdays, mean_activityImputed_weekends, all=TRUE)


# generate panel plot for weekends and weekdays
library(lattice)

xyplot(meanSteps ~ interval | week , data=weekly_trends, type="l", layout=c(1,2), ylab="Number of steps", xlab="Interval")


```

## References
https://github.com/rdpeng/RepData_PeerAssessment1/blob/master/README.md
 http://stackoverflow.com/questions/4827930/how-to-show-indexes-of-nas
 http://stackoverflow.com/questions/14634964/how-does-one-change-the-levels-of-a-factor-column-in-a-data-table




